### ISSUE TITLE
What is the difference between original fork and this?

### ISSUE THREAD

**Issue by anon-jpg** [datnguyencse/popcorn-desktop#10]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ziro-official** [comment]
Hi @anon-jpg the original popcorn-desktop has been discontinue supported from it's owners for a long time, that why I forked it and add new features, fix some bugs, merge pull request if any.

**Comment by anon-jpg** [comment]
> Hi @anon-jpg the original popcorn-desktop has been discontinue supported from it's owners for a long time, that why I forked it and add new features, fix some bugs, merge pull request if any.
> 
> Features may be add in the future: https://github.com/ziro-official/popcorn-desktop/projects/1

I know that popcorn has been discontinued. However in your todo list it’s maybe nice to add a way to crawl streams instead only torrents so the user can decide between HTTP or P2P streams. Maybe a nice idea to check out the iOS version? That’s really dead and discontinued, while Popcorn Time on different builds still working without any issues (aside from the old video codecs). I love the idea but there are much more things to resolve than just to add functionality.

If everything works out I will consider to create and sticky a post on r/PopcornTime

**Comment by ziro-official** [comment]
I have crawl all YIFY torrents to my storage server because I want to keep the old torrent which have no seed still available in the future. I'll include them to torrent as a webseed. I have no knowledge about iOS or Android so I won't support them.

Thank you.

**Comment by longnd** [comment]
hi @ziro-official, could you pls merge the pending PR and release new build?
The recurrent releases are just the source code only which is unusable for the end users.

**Comment by team-pct** [comment]
Hello, can you contact me teampct@tuta.io 
We should talk about continuing version
