### ISSUE TITLE
Will release any builds or plan to have somewhere other than github to release your fork?

### ISSUE THREAD

**Issue by ghost** [datnguyencse/popcorn-desktop#13]
Also, is there anywhere else where we can contact you? Do you have a reddit account? We're kinda thirsty on r/PopCornTime for an open source updated fork.

**Comment by ziro-official** [comment]
Dear @ghost, Of course I'll release new version, but it take time to fix some issues on both popcorn-desktop and popcorn-api. Be patient.
You can contact me via discord username: `Dat Fix#6508` or redis user `seediesio`

Thank you.
